### ISSUE TITLE
QuantityDetails?

### ISSUE THREAD

**Issue by MakakWasTaken** [RovoMe/ts-edifact#10]
I have recently tried to do some Edifact parsing with the InterchangeBuilder.
My document has some QTY elements and I saw that this elements generates the following format:
```
{
  "tag": "QTY",
  "quantityDetails": {
    "quantityTypeCodeQualifier": "136",
    "quantity": "1000"
  }
}
```
Is there a reason for adding the quantityDetails depth to the element. Why not just:
```
{
  "tag": "QTY",
  "quantityTypeCodeQualifier": "136",
  "quantity": "1000"
}
```

**Comment by RovoMe** [comment]
I just want to add some information even though you already closed the issue yourself. If you look at the [QTY definition](https://service.unece.org/trade/untdid/d01b/trsd/trsdqty.htm) you can see that `QTY` uses a complex element named ` QUANTITY DETAILS` which is just the container element for the mentioned properties. The parser itself tries to keep that structure in place when parsing the Edifact document into respective objects.

Note though that `ts-edifact` is currently not developed and supported further. We basically switched from this typescript implementation to a Java based one, also written by me but currently closed-source due to company preference, that adheres more to the actual specification than `ts-edifact` does and I am currently working on other stuff, mainly on VSCode add-ins, so that I'm not sure when to find time to update this project to a more reasonable state.
